name    	'puppet-monitis'
version 	'1.0.0'
source 		'Github'
author 		'Jan Collijs'
license 	'GPL'
summary 	'This module manages the monitis agent for monitor.us'
description 	'Using this puppet-module the monitis agent used to monitor a server against monitis.us will be maintained'
project_page 	'https://github.ugent.be/Universiteitsbibliotheek/pm_monitis'
