name    	'puppet-monitis'
version 	'1.0.0'
source 		'Github'
author 		'Jan Collijs'
license 	'GPL'
summary 	'This module manages the monitis agent'
description 	'Using this module the monitis agent from the free monitis.us service can be maintained'
project_page 	'https://github.com/visibilityspots/puppet-monitis'
