name    	'puppet-monitis'
version 	'1.0.0'
source 		'Github'
author 		'Jan Collijs'
license 	'GPL'
summary 	'This module manages the monitis agent for monitor.us'
description 	'Using this module the monitis agent to monitor a server against the free monitis.us service will be maintained'
project_page 	'https://github.ugent.be/Universiteitsbibliotheek/pm_monitis'
dependency 	'Universiteitsbibliotheek/motd', '>= 1.0.0'
